### ISSUE TITLE
Order.state values are actually fulfillment.state

### ISSUE THREAD

**Issue by core-wg-admin** [Open-network-for-digital-commerce/integration-sprint-dec21#5]
There are two values Order.state and Fulfillment.state

Order.state should have values ('ACTIVE', 'COMPLETE'  and 'CANCELLED')

Fulfillment.state descriptor. code should have values like ("SEARCHING_FOR_AGENT", "AGENT_EN_ROUTE" etc)

**Comment by core-wg-admin** [comment]
Updated the fulfillment state path from fulfillment.state to fulfillment.state.descriptor.code

**Comment by BLR-0118** [comment]
Fixed
